### ISSUE TITLE
GAE Standard - TransportError: ('Connection broken: IncompleteRead(38 bytes read)

### ISSUE THREAD

**Issue by linhtx** [firebase/firebase-admin-python#166]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Google App Engine Standard
  * Firebase SDK version: 2.10.0
  * Library version: _____
  * Firebase Product: database

#### Steps to reproduce:

I installed GAE standard (python), firebase-admin.
When use function of firebase-admin, it doesn't work.

Console output:
```logMessage:  "TransportError: ('Connection broken: IncompleteRead(38 bytes read)', IncompleteRead(38 bytes read))"     ```
#### Relevant Code:

app.yaml
```
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12
- name: ssl
  version: latest
  
env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'true'
```

appengine_config.py
```
from google.appengine.ext import vendor

# Add any libraries install in the "lib" folder.
vendor.add('lib')
```

Code
```
import firebase_admin
from firebase_admin import credentials, auth

cred = credentials.Certificate("key/asgsagahaha.json") 
default_app = firebase_admin.initialize_app(cred)

class Test():
    def __init__(self):
        pass

    def create_user(self):
        usr = auth.create_user() // Error at here
        print usr.uid
```
